In [53]:
import numpy as np

In [54]:
import pandas as pd

In [55]:
import matplotlib.pyplot as plt

In [56]:
import seaborn as sns

In [57]:
df=pd.read_csv('G:\downloads\cars\CAR DETAILS FROM CAR DEKHO.csv')

In [58]:
df

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           4340 non-null   object
 1   year           4340 non-null   int64 
 2   selling_price  4340 non-null   int64 
 3   km_driven      4340 non-null   int64 
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 186.5+ KB


In [60]:
df.isnull()

name   year  selling_price  km_driven   fuel  seller_type  \
0     False  False          False      False  False        False   
1     False  False          False      False  False        False   
2     False  False          False      False  False        False   
3     False  False          False      False  False        False   
4     False  False          False      False  False        False   
...     ...    ...            ...        ...    ...          ...   
4335  False  False          False      False  False        False   
4336  False  False          False      False  False        False   
4337  False  False          False      False  False        False   
4338  False  False          False      False  False        False   
4339  False  False          False      False  False        False   

      transmission  owner  
0            False  False  
1            False  False  
2            False  False  
3            False  False  
4            False  False  
...            ...    ...  
4335         False  False  
4336         False  False  
4337         False  False  
4338         False  False  
4339         False  False  

[4340 rows x 8 columns]

In [61]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [62]:
df.head()

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

In [63]:
df.tail()

name  year  selling_price  km_driven  \
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner

In [64]:
df['name'].value_counts()

Maruti Swift Dzire VDI                69
Maruti Alto 800 LXI                   59
Maruti Alto LXi                       47
Hyundai EON Era Plus                  35
Maruti Alto LX                        35
                                      ..
Maruti Wagon R LXI DUO BS IV           1
Tata New Safari DICOR 2.2 GX 4x2       1
Hyundai Verna 1.6 SX VTVT AT           1
Hyundai Tucson 2.0 e-VGT 2WD AT GL     1
Chevrolet Aveo 1.6 LT with ABS         1
Name: name, Length: 1491, dtype: int64

In [65]:
df['year'].value_counts()

2017    466
2015    421
2012    415
2013    386
2014    367
2018    366
2016    357
2011    271
2010    234
2019    195
2009    193
2008    145
2007    134
2006    110
2005     85
2020     48
2004     42
2003     23
2002     21
2001     20
1998     12
2000     12
1999     10
1997      3
1996      2
1995      1
1992      1
Name: year, dtype: int64

In [66]:
df['fuel'].value_counts()

Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: fuel, dtype: int64

In [67]:
df['seller_type'].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [68]:
df.head(2)

name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   

  seller_type transmission        owner  
0  Individual       Manual  First Owner  
1  Individual       Manual  First Owner

In [69]:
df.drop(columns=['name','transmission','owner'],inplace=True)

In [70]:
df.head(2)

year  selling_price  km_driven    fuel seller_type
0  2007          60000      70000  Petrol  Individual
1  2007         135000      50000  Petrol  Individual

In [71]:
dummies = pd.get_dummies(df['fuel']).rename(columns=lambda x: 'fuel_' + str(x))

In [72]:
dummies

fuel_CNG  fuel_Diesel  fuel_Electric  fuel_LPG  fuel_Petrol
0            0            0              0         0            1
1            0            0              0         0            1
2            0            1              0         0            0
3            0            0              0         0            1
4            0            1              0         0            0
...        ...          ...            ...       ...          ...
4335         0            1              0         0            0
4336         0            1              0         0            0
4337         0            0              0         0            1
4338         0            1              0         0            0
4339         0            0              0         0            1

[4340 rows x 5 columns]

In [73]:
dummies['fuel_CNG'].value_counts()

0    4300
1      40
Name: fuel_CNG, dtype: int64

In [74]:
df = pd.concat([df, dummies], axis=1)

In [75]:
df.head(3)

year  selling_price  km_driven    fuel seller_type  fuel_CNG  fuel_Diesel  \
0  2007          60000      70000  Petrol  Individual         0            0   
1  2007         135000      50000  Petrol  Individual         0            0   
2  2012         600000     100000  Diesel  Individual         0            1   

   fuel_Electric  fuel_LPG  fuel_Petrol  
0              0         0            1  
1              0         0            1  
2              0         0            0

In [76]:
df.drop(columns=['fuel'],inplace=True)

In [77]:
df

year  selling_price  km_driven seller_type  fuel_CNG  fuel_Diesel  \
0     2007          60000      70000  Individual         0            0   
1     2007         135000      50000  Individual         0            0   
2     2012         600000     100000  Individual         0            1   
3     2017         250000      46000  Individual         0            0   
4     2014         450000     141000  Individual         0            1   
...    ...            ...        ...         ...       ...          ...   
4335  2014         409999      80000  Individual         0            1   
4336  2014         409999      80000  Individual         0            1   
4337  2009         110000      83000  Individual         0            0   
4338  2016         865000      90000  Individual         0            1   
4339  2016         225000      40000  Individual         0            0   

      fuel_Electric  fuel_LPG  fuel_Petrol  
0                 0         0            1  
1                 0         0            1  
2                 0         0            0  
3                 0         0            1  
4                 0         0            0  
...             ...       ...          ...  
4335              0         0            0  
4336              0         0            0  
4337              0         0            1  
4338              0         0            0  
4339              0         0            1  

[4340 rows x 9 columns]

In [80]:
dummies1=pd.get_dummies(df['seller_type']).rename(columns=lambda x: 'seller_' + str(x))

In [81]:
dummies1

seller_Dealer  seller_Individual  seller_Trustmark Dealer
0                 0                  1                        0
1                 0                  1                        0
2                 0                  1                        0
3                 0                  1                        0
4                 0                  1                        0
...             ...                ...                      ...
4335              0                  1                        0
4336              0                  1                        0
4337              0                  1                        0
4338              0                  1                        0
4339              0                  1                        0

[4340 rows x 3 columns]

In [82]:
df=pd.concat([df,dummies1],axis=1)

In [83]:
df.head(2)

year  selling_price  km_driven seller_type  fuel_CNG  fuel_Diesel  \
0  2007          60000      70000  Individual         0            0   
1  2007         135000      50000  Individual         0            0   

   fuel_Electric  fuel_LPG  fuel_Petrol  seller_Dealer  seller_Individual  \
0              0         0            1              0                  1   
1              0         0            1              0                  1   

   seller_Trustmark Dealer  
0                        0  
1                        0

In [84]:
df.drop(columns=['seller_type'],inplace=True)

In [85]:
df.head(2)

year  selling_price  km_driven  fuel_CNG  fuel_Diesel  fuel_Electric  \
0  2007          60000      70000         0            0              0   
1  2007         135000      50000         0            0              0   

   fuel_LPG  fuel_Petrol  seller_Dealer  seller_Individual  \
0         0            1              0                  1   
1         0            1              0                  1   

   seller_Trustmark Dealer  
0                        0  
1                        0

In [86]:
x=df.iloc[:,[0,2,3,4,5,6,7,8,9,10]].values

In [87]:
x

array([[  2007,  70000,      0, ...,      0,      1,      0],
       [  2007,  50000,      0, ...,      0,      1,      0],
       [  2012, 100000,      0, ...,      0,      1,      0],
       ...,
       [  2009,  83000,      0, ...,      0,      1,      0],
       [  2016,  90000,      0, ...,      0,      1,      0],
       [  2016,  40000,      0, ...,      0,      1,      0]], dtype=int64)

In [88]:
y=df.iloc[:,1].values

In [89]:
y

array([ 60000, 135000, 600000, ..., 110000, 865000, 225000], dtype=int64)

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [92]:
x_train

array([[ 2014, 92000,     0, ...,     1,     0,     0],
       [ 2016, 70000,     0, ...,     0,     1,     0],
       [ 2012, 54000,     0, ...,     1,     0,     0],
       ...,
       [ 2016, 22000,     0, ...,     0,     1,     0],
       [ 2015, 70000,     0, ...,     0,     1,     0],
       [ 2013, 62000,     0, ...,     0,     1,     0]], dtype=int64)

In [93]:
x_test

array([[  2012,  70070,      0, ...,      1,      0,      0],
       [  2013,  86000,      0, ...,      1,      0,      0],
       [  2014, 120000,      0, ...,      0,      1,      0],
       ...,
       [  2014,  90000,      0, ...,      0,      1,      0],
       [  2015,  21000,      0, ...,      1,      0,      0],
       [  2013, 125531,      0, ...,      1,      0,      0]], dtype=int64)

In [94]:
y_train

array([525000, 650000, 235000, ..., 270000, 600000, 229999], dtype=int64)

In [95]:
y_test

array([ 465000, 1580000,  150000, ...,  350000,  295000,  600000],
      dtype=int64)

In [100]:
from sklearn.tree import DecisionTreeRegressor

In [101]:
dtg=DecisionTreeRegressor()

In [102]:
dtg.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [103]:
y_pred=dtg.predict(x_test)

In [104]:
y_pred

array([ 440000., 1580000.,  300000., ...,  175000.,  270000.,  315000.])

In [115]:
pred=dtg.predict([[2012,230000,0,0,1,0,0,1,0,0]])

In [116]:
pred

array([850000.])

In [117]:
df1 = pd.DataFrame({'Real Values':y_test.reshape(-1), 'Predicted Values':y_pred.reshape(-1)})

In [118]:
df1

Real Values  Predicted Values
0          465000      4.400000e+05
1         1580000      1.580000e+06
2          150000      3.000000e+05
3         4950000      4.950000e+06
4          125000      1.250000e+05
...           ...               ...
1080       500000      5.000000e+05
1081       465000      4.652857e+05
1082       350000      1.750000e+05
1083       295000      2.700000e+05
1084       600000      3.150000e+05

[1085 rows x 2 columns]